# Generated by Django 6.1.1 on 2026-09-16 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('bust', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tour de poitrine (cm)')),
                ('waist', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tour de taille (cm)')),
                ('hips', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tour de hanches (cm)')),
                ('shoulders', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Largeur des épaules (cm)')),
                ('desired_length', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Longueur souhaitée (cm)')),
                ('sleeve_length', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Longueur des manches (cm)')),
                ('extra_notes', models.TextField(blank=True, verbose_name='Informations complémentaires')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Article du panier',
                'verbose_name_plural': 'Articles du panier',
            },
        ),
    ]
