# Generated by Django 6.1.1 on 2026-09-16 22:27

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, unique=True, verbose_name='Ville')),
                ('fee', models.PositiveIntegerField(verbose_name='Frais (FCFA)')),
            ],
            options={
                'verbose_name': 'Frais de livraison',
                'verbose_name_plural': 'Frais de livraison',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=orders.models.generate_order_reference, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=80, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=80, verbose_name='Nom')),
                ('phone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('country', models.CharField(default='Sénégal', max_length=100, verbose_name='Pays')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Quartier')),
                ('full_address', models.TextField(verbose_name='Adresse complète')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('extra_info', models.CharField(blank=True, max_length=255, verbose_name='Indication complémentaire')),
                ('shipping_fee', models.PositiveIntegerField(default=0, verbose_name='Frais de livraison (FCFA)')),
                ('shipping_note', models.CharField(blank=True, max_length=255, verbose_name='Note livraison')),
                ('subtotal', models.PositiveIntegerField(default=0, verbose_name='Sous-total (FCFA)')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Total (FCFA)')),
                ('status', models.CharField(choices=[('pending_payment', 'En attente de paiement'), ('paid', 'Paiement confirmé'), ('confirmed', 'Commande confirmée'), ('preparing', 'En préparation'), ('ready', 'Prête'), ('shipping', 'En livraison'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending_payment', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('unit_price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bust', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('hips', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('shoulders', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('desired_length', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('sleeve_length', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('extra_notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
            },
        ),
    ]
